# Generated by Django 5.1.4 on 2026-02-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_receiver_email_shipmentupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
