# Generated by Django 5.1.4 on 2026-02-04 19:26

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_current_lat_shipment_current_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='current_location',
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
