# Generated by Django 5.1.4 on 2026-02-07 12:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_remove_shipment_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
