# Generated by Django 5.1.4 on 2026-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_shipment_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Courier'), ('overnight', 'Overnight Shipping')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
