# Generated by Django 5.1.4 on 2026-02-07 13:03

import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_estimated_delivery_shipment_receiver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default=shipments.models.generate_tracking_number, max_length=20, unique=True),
        ),
    ]
