# Generated by Django 5.1.4 on 2026-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_rename_estimated_delivery_shipment_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(blank=True, choices=[('dhl', 'DHL'), ('fedex', 'FedEx'), ('global_express', 'Global Express Logistics'), ('usps', 'USPS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='mode',
            field=models.CharField(blank=True, choices=[('sea', 'Sea'), ('land', 'Land'), ('air', 'Air')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bac', 'BAC'), ('paypal', 'PayPal'), ('zelle', 'Zelle'), ('crypto', 'Crypto')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='type_of_shipment',
            field=models.CharField(blank=True, choices=[('air_freight', 'Air Freight'), ('truckload', 'Truckload'), ('international_shipping', 'International Shipping'), ('van_move', 'Van Move'), ('office_pickup', 'Office Pickup')], max_length=50, null=True),
        ),
    ]
