# Generated by Django 5.1.4 on 2026-02-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_alter_shipment_carrier_alter_shipment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='packages_count',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
