# Generated by Django 5.1.4 on 2026-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_remove_shipment_agent_name_remove_shipment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='current_status_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
