# Generated by Django 5.1.4 on 2026-02-07 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_remove_shipment_comments_remove_shipment_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentupdate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shipment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentupdate',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentupdate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentupdate',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentupdate',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('piece_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('length', models.FloatField(default=0.0, verbose_name='Length(cm)')),
                ('width', models.FloatField(default=0.0, verbose_name='Width(cm)')),
                ('height', models.FloatField(default=0.0, verbose_name='Height(cm)')),
                ('weight', models.FloatField(default=0.0, verbose_name='Weight(kg)')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shipments.shipment')),
            ],
        ),
    ]
