# Generated by Django 5.1.4 on 2026-02-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_remove_shipmentupdate_updated_at_shipment_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_address',
            field=models.CharField(max_length=255),
        ),
    ]
