# Generated by Django 5.1.4 on 2026-02-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_alter_shipment_receiver_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dest_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
